### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by karpovalexandrn** [ruOpenCart/assembly-configurator#1]
Здравствуйте, 

при попытке выключения выходит ошибка следующего вида:

`Warning: Use of undefined constant VERSION_RE - assumed 'VERSION_RE' (this will throw an Error in a future version of PHP) in /home/XXXXXXX/ИМЯ.САЙТА/docs/admin/controller/extension/module/assembly_configurator/assembly_configurator_info.php on line 15
Fatal error: Uncaught UnexpectedValueException: FilesystemIterator::__construct(/home/XXXXXXX/ИМЯ.САЙТА/storage/ocn/modifications/): failed to open dir: No such file or directory in /home/XXXXXXX/ИМЯ.САЙТА/docs/admin/controller/extension/module/assembly_configurator/assembly_configurator_general.php:22 Stack trace: #0 /home/XXXXXXX/ИМЯ.САЙТА/docs/admin/controller/extension/module/assembly_configurator/assembly_configurator_general.php(22): FilesystemIterator->__construct('/home/h81229773...') #1 /home/XXXXXXX/ИМЯ.САЙТА/storage/modification/system/engine/action.php(79): ControllerExtensionModuleAssemblyConfiguratorAssemblyConfiguratorGeneral->getFiles(Array) #2 /home/XXXXXXX/ИМЯ.САЙТА/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array) #3 /home/XXXXXXX/ИМЯ.САЙТА/docs/admin/controller/extension/module/assembly_configurator/assembly_configurator_modification.php(80): Loader->controller in /home/XXXXXXX/ИМЯ.САЙТА/docs/admin/controller/extension/module/assembly_configurator/assembly_configurator_general.php on line 22`

Пожалуйста подскажите как исправить?

**Comment by karpovalexandrn** [comment]
Решено.
Необходимо папку ocn из storage скопировать в свою перемещенную.
